
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: connector
    component: cron-connector
  name: sample-connector
  namespace: openfaas
spec:
  selector:
    matchLabels:
      app: connector
  replicas: 1
  template:
    metadata:
      labels:
        app: connector
        component: cron-connector
    spec:
      containers:
      - name: cron-connector
        image: zeerorg/cron-connector:v0.2.2
        env:
          - name: gateway_url
            value: "http://gateway.openfaas:8080"
          - name: basic_auth
            value: "true"
          - name: secret_mount_path
            value: "/var/secrets/"
        volumeMounts:
            - name: auth
              readOnly: true
              mountPath: "/var/secrets/"
      volumes:
      - name: auth
        secret:
          secretName: basic-auth
