version: '3.2'
services:
  cron-connector:
    image: zeerorg/cron-connector:v0.2
    hostname: cron-connector
    environment:
      gateway_url: "http://gateway:8080"
      basic_auth: "true"
      secret_mount_path: "/run/secrets/"
    secrets:
      - basic-auth-password
      - basic-auth-user
    networks:
      - func_functions

networks:
  func_functions:
    external: true

secrets:
    basic-auth-user:
        external: true
    basic-auth-password:
        external: true
